### ISSUE TITLE
random game at specified folder

### ISSUE THREAD

**Issue by SamYStudiO** [DanTheMan827-Hakchi/random-hakchi-game#2]
Could you point me out how i can launch a random game from path containing a specified pattern.
I have both english and french games and i'd like to have  a random game launcher for both language. Every english game are in a folder name containing "English" and every french game are in a folder containing "Français"

Thx a lot!

**Comment by SamYStudiO** [comment]
found a solution

**Comment by vulfgang** [comment]
SamYStudio I want to do something similar, how did you resolve this issue? I want to be able to randomize folders (i.e. sega, mame, snes, etc) rather than the whole system

**Comment by vulfgang** [comment]
SamYStudio I want to do something similar, how did you resolve this issue? I want to be able to randomize folders (i.e. sega, mame, snes, etc) rather than the whole system
